sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=arm
    - ARCH=amd64
#    - ARCH=arm64

script:
  - ./build.sh
  - ./test.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      # push image
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./deploy.sh
    fi
